### ISSUE TITLE
API code release process: interfere with indexing?

### ISSUE THREAD

**Issue by pkshiu** [OpenConceptLab/oclapi#114]
This is really more a set of questions around the indexing and API code release process:

* currently the API code release completely rebuild the schema for solr as part of the release, is this the correct behavior? Will it affect the current index?
* after import of data, should we always rebuild the solr index via haystack? Should we do update_index? This will be relevent as we import more data sources
* If solr dies, which seems to happen randomly, what is the correct process for recovery? If a reindexing is going on and solr dies, what should we do?
* Is there a way to monitoring rebuilding of index (-v2 does not seems to do much with the rebuild_index command). Is there a way to query the index at command line?

**Comment by paynejd** [comment]
@pkshiu Is this complete? Do you need some of these questions answered still?

**Comment by pkshiu** [comment]
Yes @MisterNando if you can answer these questions that would be very helpful going forward

**Comment by MisterNando** [comment]
Q: currently the API code release completely rebuild the schema for solr as part of the release, is this the correct behavior? Will it affect the current index?

A: It is unnecessary unless the Solr index schema has changed since the last release.  In any event, Solr does not go offline while the index rebuilds; the rebuild occurs in the background, and then the indices are swapped out upon completion.

Q: after import of data, should we always rebuild the solr index via haystack? Should we do update_index? This will be relevent as we import more data sources

A: Yes, the index must remain in sync with the data at all times.  You can run a more targeted version of update_index by specifying the command line arguments --age or --start and --end.

Q: If solr dies, which seems to happen randomly, what is the correct process for recovery? If a reindexing is going on and solr dies, what should we do?

A: I don't know of any clean way to recover from a Solr crash during an index update.  However, if a crash occurs while an update is NOT in progress, a simple restart should be sufficient to recover (and maybe an update_index with --start=[time of the crash]).

Q: Is there a way to monitoring rebuilding of index (-v2 does not seems to do much with the rebuild_index command). Is there a way to query the index at command line?

A: Not that I'm aware of.  I usually tail the Solr logs, which update upon completion of each batch (default batch size is 1000 records).
