### ISSUE TITLE
Add HTTPS/SSH support to all 3 server environments

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/oclapi#137]
Right now all access is via http, which is clearly not secure

**Comment by AnjaliWadhwa** [comment]
SSL certificate is implemented in staging and production environment. 

This is a free certificate which is valid only for 3 months. In order to renew the certificate once expired, we have added a crontab entry in both staging and production. This crontab entry will check for certificate validity daily at 5:00 AM , and renew the certificate if required.

This ssl certificate (https) is attached to ocl_web only.

This free certificate is taken from "letsencrypt" community. Below is the link you can refer if you want to know more about this.

https://certbot.eff.org/#ubuntuxenial-nginx

**Comment by AnjaliWadhwa** [comment]
Created #280 for SSL in OCL API
