### ISSUE TITLE
Freeze version of source

### ISSUE THREAD

**Issue by snyaggarwal** [OpenConceptLab/oclapi#167]
Tasks:
1. Name auto-generated version of source as "head"
2. Put all updates on "head" (need to empty search on head to view all)
3. Ensure no updates on versioned objects
4. HEAD version should not be released by default
5. No updated information of concepts in previous versions of source
6. No "New Concept" button in source versions except HEAD i.e new concepts will be added in Head only. 
7. Edit of a versioned concept shouldnt be allowed on UI
8. Default order is HEAD first and then other versions (order by updated_at)

**Comment by paynejd** [comment]
Text from an old ticket on this topic...

The implementation of source versions is actually quite different than intended, although there was enough wiggle room in the spec that the approach taken makes sense. OCL source versions were intended to work the same way that GitHub repository tags work -- i.e. they capture a source at a specific point in time and they cannot be changed after created. 

The correct Source versions implementation is as follows:
* The automatically generated source version should be called "head" instead of a randomly generated string
* All edits to a source are always captured by the "head" source version
* All manually created source versions capture the state of the source at the time that the source version is created (i.e. it makes a copy of the "head") and the concepts/mappings that they reference are not changed
* However, limited source version metadata may be updated later (e.g. description, etc.)
* Source versions should capture all source metadata and save it (e.g. total and active number of concepts, mappings, the timestamp of the most recent update to a child concept/mapping, full name, description, extras, etc.)
* Exports should be modified to export the source metadata that was saved to the source version so that they will have the correct number of concepts, mappings, etc.
* NOTE that this ticket will also address #131

Note that this is a more complicated update and must be discussed before development begins.

**Comment by paynejd** [comment]
This is working as expected.
