### ISSUE TITLE
Fix Mappings unit tests

### ISSUE THREAD

**Issue by snyaggarwal** [OpenConceptLab/oclapi#181]
- db cleanup (tearDown) -- Done
- generic mixins handling (head not released etc.) -- Done
- validations errors (same external_id and permissions)

**Comment by snyaggarwal** [comment]
failing tests (skipped now):
mappings.MappingClassMethodsTest.test_persist_new_negative__same_mapping
mappings.MappingTest.test_create_mapping_negative__same_mapping_type1
mappings.MappingTest.test_create_mapping_negative__same_mapping_type2
integration_tests.MappingCreateViewTest.test_mappings_create_positive__other_org_owner

**Comment by paynejd** [comment]
Let me indicate the expected behavior in each of these situations (assuming that I correctly understand what is being tested). With all of them, I am unclear as to why they are not passing because it appears to be the correct behavior, although I am not familiar enough with the code to know if something is incorrect within the tests.

**1. test_persist_new_negative__same_mapping** - My understanding is that this test is asserting that no two mappings should exist within a single source in which mapType, fromConcept and toConcept are the same. Ex. you cannot create two mappings within the same source that say "CIEL:123 is the same as ICD-10:A15.1". If I understand this correctly, then I thought that this test should pass! I think that the developer may have dropped the unique mapping constraint in order to speed up the imports, but that is not correct behavior.

**2. test_create_mapping_negative__same_mapping_type1** - This test seems to be creating a Type 1 "Internal" mapping (i.e. both the from and to concept are stored in OCL) and simply verifying that its attributes match what was created. If my understanding is correct, then this seems valid! Why wouldn't this be passing?

**3. test_create_mapping_negative__same_mapping_type2** - This test seems to be creating a Type 2 "External" mapping (i.e. the from concept and to source are stored in OCL but the to concept not stored in OCL) and simply verifying that its attributes match what was created. If my understanding is correct, then this seems valid! Why wouldn't this be passing?

** test_mappings_create_positive__other_org_owner** - This test seems to be creating a new Type 1 "internal" mapping within a source owned by an organization and simply asserting that it exists. This seems entirely valid. Why wouldn't this be passing? Also, how is this test different than the type1 test above?

**Comment by paynejd** [comment]
Re-reading your email, I think I did not correctly understand the intent of the tests. Thoughts:
* "external_id" should be unique within a single source - this is used by the importing tool to match up resources from external  dictionaries, such as CIEL
* regarding mapping creation, the permissions currently depend on one thing: The user should have the ability to create a mapping with _any_ fromConcept/toConcept as long as it has permissions to edit the source to which the mapping will be added -- meaning, it doesn't matter which sources the from/to concepts are in, it only matters which source the mapping is being added to. From what you described, the test should fail if the user does not have editing rights to the source.

Does that clarify better?

**Comment by snyaggarwal** [comment]
- "external_id" -- shall we re-introduce the uniqueness clause? Do you know where it will effect around performance or import?
- creation of mapping in a source -- this makes sense and the code is written accordingly,  will fix the test.

**Comment by snyaggarwal** [comment]
Integration test with permission issue is fixed -- test_mappings_create_positive__other_org_owner -- the test wasn't login-in with the right user.

**Comment by snyaggarwal** [comment]
There used to be a (Django) uniqueness constraint on Mapping, removed in commit: 25727bcdaf56cc66f47630c65c89552ea4cd8611 as part of #113 

On reverting this, the three remaining tests seems to pass. But looks like #113 was done intentionally to handle some specific issue, please take a look and advice, shall I delete these tests or revive the code for uniqueness.

**Comment by paynejd** [comment]
Hi Sunny,

Based on #113, there was an incorrect unique constraint on `source + fromConcept + mapType` that was removed. The unique constraint should have been on `source + fromConcept + mapType + toConcept`. Is the latter indexed at all and does it have a unique constraint? If not, creating that index may allow those tests to pass, but I do not understand the test code well enough to know if that is true or not.

Jon

**Comment by snyaggarwal** [comment]
I have added the constraint:
source + fromConcept + mapType + toConcept

Tests passed!
