### ISSUE TITLE
Include retired concepts in CSV download by default

### ISSUE THREAD

**Issue by AnjaliWadhwa** [OpenConceptLab/oclapi#275]
We have CSV download at Global search and Repository level, by default we need to include retired concepts in both type of CSV downloads.

**Comment by paynejd** [comment]
Repository download should default to including retired concepts and
mappings.

Search-based CSV downloads should reflect the search criteria, and only
include retired if that is part of the search criteria.

On Mon, Oct 17, 2016, 10:40 AM AnjaliWadhwa <notifications@github.com>
wrote:

We have CSV download at Global search and Repository level, by default we
need to include retired concepts in both type of CSV downloads.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/OpenConceptLab/oclapi/issues/275>, or mute the thread
