### ISSUE TITLE
Basic - validate concepts on edit

### ISSUE THREAD

**Issue by fatmau** [OpenConceptLab/oclapi#277]
As a user
I want to edit a concept without Open MRS validation schema
So that I can create a concept matching with basic validation rules.

**Acceptance Criteria:**
When editing concept, do below validations;
- validate concept name

**Comment by fatmau** [comment]
below tests will be run at related create stories.

**Acceptance Criteria:**
When editing concept, do below validations;
- validate concept lookup attributes
- validate concept attributes not empty

When editing map, do below validations;
- validate map references
- validate map attributes not empty

**Comment by djazayeri** [comment]
I verified that I cannot edit a concept in a source with Basic validation so that (a) it duplicates the preferred name of another concept, or (b) does not have a fully-specified name.

I don't understand what "validate concept lookup attributes" means from the earlier comment.

Side-note: from the user standpoint it would be very nice if the error message "Concept preferred name must be unique for same source and locale" could link to or give the ID of the duplicate concept.
