### ISSUE TITLE
Index 'to_concept_code' from mappings

### ISSUE THREAD

**Issue by AnjaliWadhwa** [OpenConceptLab/oclapi#279]

**Comment by AnjaliWadhwa** [comment]
We should index below fields for mappings:
* fromConcept - mapping.from_concept_code OR mapping.from_concept_name
* toConcept - mapping.to_concept_code OR mapping.to_concept_name

Also we are indexing 'External Id' for mappings. We need to keep it but just lower the weight of external_id in indexing.

**Comment by mKadiyan** [comment]
- for from concept
     - owner (i.e. user or orgs)
     - source
     - concept code 
    - mnemonic
    - external_id

- for to concept (only for external mapping)
     - owner (i.e. user or orgs)
     - source
     - concept code
     - concept name
     - mnemonic
     - external_id 

Although, "for to concept"  code exist to make the searchable, but its not working properly.

for #279 , below are the things  are planned : 
1. fix the bug because of which "to concept"  search not working
2. make "to concept" searchable for Internal Mapping too.

**Comment by AnjaliWadhwa** [comment]
This seems to be working fine on showcase now.

**Comment by paynejd** [comment]
I think that this is working, but worth confirming...
