### ISSUE TITLE
OpenMRS - add concept/mapping reference to collection

### ISSUE THREAD

**Issue by fatmau** [OpenConceptLab/oclapi#302]
As a user
I want to add concept or mapping reference to a collection 
So that I can connect concepts/mappings and collections in terms of validation rules.

__Acceptance Criteria:__

When adding a concept/mapping reference to a collection via UI, run below business rules;
* at "Add Single Reference" page; 
     * if user enters URL without version information, add the latest version id to the reference expression while saving the reference. Then **warn** user as; 
            *  ```OCL does not support adding the HEAD version of concepts to the collection. Added the latest version instead: {{source+mnemonic}} version {{version}}```
            *  ```OCL does not support adding the HEAD version of mapping to the collection. Added the latest version instead: {{source+mnemonic}} version {{version}}```
     *  if user enters URL with version information, add that version of concept/mapping to collection. Then **inform** user as;
            *  ``` Added concept: {{source+mnemonic}} version {{version}} ```
             * ``` Added mapping: {{source+mnemonic}} version {{version}} ```

* at "Add Multi References" page; 
     * If user selects HEAD version of source from dropdown, show below **warning** just below the dropdown.
             * ``` When HEAD version selected, the latest version of concepts/mappings are listed```
     * If user selects HEAD version of source from dropdown and wants to add some concepts/mappings to collection, add the latest (or current) version of concepts/mappings to collection. Then inform user as;
            * ``` The latest versions of concepts/mappings are added to collection, and they will not be affected from future updates.```
     * If user selects non-HEAD version of source from dropdown and wants to add some concepts/mappings to collection, add the related versions of concepts/mappings (which are belongs to that specific non-HEAD version of source) to the collection. Then inform user as;
             ``` The concepts/mappings are added to collection.```

When adding a concept/mapping reference to a collection via API, run below business rules;
*  if version number of concept/mapping is not specified in URL, add the latest (or current) version of concept/mapping to collection. Then **warn** user as; 
             * ``` The latest version of concept XXX is added to collection, and it will not be effected from future updates. ```
            * ``` The latest version of mapping XXX is added to collection, and it will not be effected from future updates.```
* if version number of concept/mapping is specified in URL, add that version of concept/mapping to collection. Then **inform** user as;
             * ``` The concept XXX is successfully added to collection YYY ```
             * ``` The mapping XXX is successfully added to collection YYY ```

When adding a concept/mapping reference to a collection via UI or API, do below Open MRS validations;
* concept reference name (which is the concept URL **without version data**) should be unique in collection. In case of error, show below warning;
             * ```Reference must be unique in a collection.```
* "fully specified name" need to be unique (by locale) within a collection, e.g. you cannot have two concepts called "pulmonary hypertension". In case of error, show below warning;
            * ```Concept fully specified name must be unique for same collection and locale.```
*  "preferred name" need to be unique (by locale) within a collection. In case of error, show below warning;
             * ``` Concept preferred name must be unique for same collection and locale.```

PS1: While developing, assume that reference name already exists

**Comment by paynejd** [comment]
1 modifications to make to the above description:

The requirement should be that only versioned concepts/mappings are added to collections with the OpenMRS validation schema. If a user attempts to add an non-versioned concept or mapping (e.g. `/orgs/CIEL/sources/CIEL/concepts/3/` or `/orgs/CIEL/sources/CIEL/HEAD/concepts/3/`) it could simply be resolved to a a versioned concept or mapping (e.g. the above links would both be resolved to `/orgs/CIEL/sources/CIEL/concepts/3/[concept_version_number]/`). This is the same behavior as when adding a concept/mapping from a source version -- the concept/mapping is resolved to the versioned concept/mapping.

This behavior of resolving non-versioned references to versioned references is already pretty confusing, and I think will be more so if there is different behavior based on validation schema. There is a minimum requirement that the is notified when a reference is resolved to a versioned resource. Even better, we could add a checkbox or a popup window in the UI that gives the user control over how and whether a non-versioned reference is resolved to a versioned reference. Of course, if adding to a collection with OpenMRS validation, the user will be required to resolve it to versioned.

**Comment by fatmau** [comment]
instead of dealing with HEAD, we can add latest version of content!

**Comment by djazayeri** [comment]
The changes look good. (Basically we decided to go with @paynejd 's idea that if the user tries to add a non-versioned reference, we substitute in a reference to the current latest version.)

I would change the wording of the messages like:

* When we substitute in a fixed version, for Add Single
 * "{{validation scheme name}} does not support adding the HEAD version of concepts to the collection. Added the latest version instead: {{source+mnemonic}} version {{version}}"
 * "{{validation scheme name}} does not support adding the HEAD version of mappings to the collection. Added the latest version instead: {{source+mnemonic}} version {{version}}"
* When the user specified a version for Add Single (I assume this is on the collection page, so we don't need to indicate the collection name in the success message)
 * "Added concept: {{source+mnemonic}} version {{version}}"
 * "Added mapping: {{source+mnemonic}} version {{version}}"

**Comment by djazayeri** [comment]
Testing on staging.ocl.org with an OpenMRS-validated collection:

* Add Single Reference
  * Functionality is right.
  * Display message is wrong: it doesn't show the validation schema name, or the source name. Actual: "Does not support adding the HEAD version of concepts to the collection. Added the latest version instead: 128125 version 57cd6d48fffcf000075c89b1". Expected: as in my previous comment on this issue.
  * Display message for adding a single mapping is similarly incorrect
  * adding a single concept or mapping with a version number also fails to display the source in the feedback message.
  * Unexpected behavior when adding a single concept (I don't know if this is a regression or if it always worked that way): I am not allowed to add this reference: "/orgs/CIEL/sources/CIEL/concepts/122746/57cd690afffcf000075c648d" but if I put a / at the end, it's allowed. Ideally we would allow both, but standardize to a canonical form. (This is of trivial priority.)
* Add Multiple References
   * "If user selects HEAD version of source from dropdown, show below warning just below the dropdown." => the warning slides in at the top right and then disappears. That's not what's specified in the ticket, though I don't care that much. It would be nice to have a consistent UI approach though.
   * On staging I chose CIEL, CIEL, HEAD, and typed "hematocrit". When I checked the box for the first concept I get this error as a browser popup: http://pastebin.com/cya5BhVK
   * After I dismissed the popup, behavior seems like it was correct.
   * Please change the wording from this "The latest versions of concepts/mappings are added to collection, and they will not be affected from future updates." to instead say "Added the latest versions of concepts/mappings to the collection. Future updates will not be added automatically."
   * Adding from a past source version, please change the message from "The concepts/mappings are added to collection." to "Concepts/mappings added to collection"
   * In the tests above I didn't actually verify what happens when there *are* multiple versions, but the first time I'm testing by creating a version of a source, and then editing a concept in it afterwards, the behavior is wrong:
   * I say User:djazayeri, Source:OMRS, version:1.0, then search "weight"...
      * search result under concepts shows "Last updated on" with a date that is for the latest concept edit, not the one that should be in the source version.
      * when I select that concept and Add it, the reference added is for the _latest_ version of the concept, not the version that's in the source version I selected. (E.g. the version of that concept under under https://staging.openconceptlab.org/users/djazayeri/sources/OMRS/1.0/concepts/ is 5826... but the version that was actually added is 588f...

I will stop testing here. Let me know when these are fixed.

**Comment by djazayeri** [comment]
Here are specific instructions to reproduce the versioning bug:

1. New Source "302" with locale en and OpenMRS validation
  * https://staging.openconceptlab.org/users/djazayeri/sources/302/
2. New Concept, id=302, name=302v1
  * https://staging.openconceptlab.org/users/djazayeri/sources/302/concepts/302/
3. Go to Source 302 -> Versions -> New Version "1.0"
  * https://staging.openconceptlab.org/users/djazayeri/sources/302/1.0/
4. Go to Concept 302, edit and change name to 302v2
  * https://staging.openconceptlab.org/users/djazayeri/sources/302/concepts/302/
5. Go to Version 1.0 Concept and see that the concept name is 302v1
  * https://staging.openconceptlab.org/users/djazayeri/sources/302/1.0/concepts/
  * https://staging.openconceptlab.org/users/djazayeri/sources/302/concepts/302/5893b5b98edb9b001aef1669
  * if it matters, the versions display is chronological, _not_ reverse-chronological at https://staging.openconceptlab.org/users/djazayeri/sources/302/versions/ 
6. Create new collection "302", locale en, validation OpenMRS
  * https://staging.openconceptlab.org/users/djazayeri/collections/302/
7. In that collection -> References -> New Reference -> Add multiple references -> user:djazayeri, source:302, version 1.0
  * https://staging.openconceptlab.org/users/djazayeri/collections/302/references/new/
  * it seems to show the correct version in the left column ("302v1")
  * but when I click on it, the wrong version opens in a new tab
    * https://staging.openconceptlab.org/users/djazayeri/sources/302/concepts/302/
  * when I check the box and say Add, the wrong version ("302v2") is added
    * https://staging.openconceptlab.org/users/djazayeri/collections/302/references/
