### ISSUE TITLE
Concept Validation Order

### ISSUE THREAD

**Issue by fatmau** [OpenConceptLab/oclapi#342]
Acceptance Criteria:

At both Basic and Open MRS schema, concept validation order must be like below;
1. validations on the concept itself
2. validations on related locale
3. validations on belonging source

PS: This story is "nice to have", has low priority

**Comment by emrah-b** [comment]
@fatmau @djazayeri I suggest removing item #2, we can implement 1 and 3 easily by rearranging method calls, but implementing #2 will introduce unnecessary complexity

What say you?

**Comment by emrah-b** [comment]
@fatmau @djazayeri on a second thought, let's push this back if it's low priority. As of now, we run rules for basic schema then we run the rules for OpenMRS schema. 

Validation order will hold within the schema but not across schemas. In other words:

1) Run concept based validations for basic schema
2) Run source based validation for basic schema
3) Run concept based validations for OpenMRS schema
4) Run source based validations for OpenMRS schema

**Comment by djazayeri** [comment]
@emrah-b my original comment was on #241, and said

> When I try to create a concept which has 2 copies of the same name, and I mark them both as preferred, the error message is "Concept preferred name must be unique for same source and locale". However I would have expected to see the error message for one of the constraints I failed on this concept itself.

I don't know if the cause is incorrect order of validations, incorrect logic, or a misleading error message.

My actual goal is:

* if the concept fails internal validation, the error message should reflect this (e.g. in this case "cannot have two preferred names in a locale")
* checking for duplicates elsewhere in the source/collection should only be checking against other concepts (e.g. the error message I saw made me think the system was checking for duplicates across the source)

**Comment by emrah-b** [comment]
@djazayeri got it! our fix covers that
