### ISSUE TITLE
Concept / Global Search / Search, select and add (without collection)

### ISSUE THREAD

**Issue by fatmau** [OpenConceptLab/oclapi#422]
As a user
I want to select and add any concept to collection
So that I will see information when I do not have existing collection.

**Dependency:**

- #406 

**Acceptance Scenario:**

| No  | Given  | When  | Then  |
| ------------- | ------------- | ------------- | ------------- |
| 1 | I searched for concept with one or multiple result | I clicked on "+ Add to Collection" link  | the result list will become a selectable table |
| 2 | Scenario No 1  | I select one or multiple results | Add to Collection link becomes a dropdown  |
| 3 | Scenario No 2  | I do not have existing collection | Information (create a collection in your profile) will be in the dropdown  |
| 4 | Scenario No 3  | I unselect all the concepts  | Add to collection returns a Cancel button.

**Mock-ups:**

- Mock-ups can be found at this URL --> https://marvelapp.com/14d1eb3/screen/24745968
-Check the link below to see the pages
https://drive.google.com/drive/u/0/folders/0B2RCqE113zNxNm9wdThQVXVvaEk

**Technical Assumptions:**

- This is for the Logged-in User.
- No need to consider If the user has collection.

**Comment by djazayeri** [comment]
Scenario 2 and 4 work correctly as-written. (Though we would like to change the behavior so that the checkboxes are always there, as mentioned on other stories.)

For Scenario 3:

* change the text to "You do not have any existing collections. (link)Create a collection(/link) in your profile."
* currently there is some blue text but it's not a clickable link. Either the text should be normal, or else it should be a link that automatically takes you to your profile screen.
* Honestly I don't actually link having this link because it's not obvious that your first step should be to create a collection in *your own* profile and not in an organization. But I think @paynejd wants it this way, so that's fine.

**Comment by berkansahan** [comment]
This is a good idea to have the link in dropdown to take user automatically to their profile screen but in this situation it is better to create an another story for this. That's why, here we do suggest to write as a normal text. If we need it, we should implement it later.
Here are the links to see updated version of the story.
* Mock-ups: https://marvelapp.com/14d1eb3/screen/25608669 
* Drive: https://drive.google.com/drive/u/0/folders/0B2RCqE113zNxNm9wdThQVXVvaEk

**Comment by djazayeri** [comment]
Okay sounds good.
