### ISSUE TITLE
Concept / Repository Search / Search, select and add (without collection)

### ISSUE THREAD

**Issue by fatmau** [OpenConceptLab/oclapi#426]
As a user
I want to select and add any concept to collection
So that I will see information when I do not have existing collection.

**Dependency:**

- #425  

**Acceptance Scenario:**

| No  | Given  | When  | Then  |
| ------------- | ------------- | ------------- | ------------- |
| 1 | I list the concepts | I select any concept with chekboxes  | Disabled 'Add to Collection' button becomes enabled (clickable) |
| 2 | Scenario No 1  | 'Add to Collection' button becomes enabled | Add to Collection link becomes a dropdown  |
| 3 | Scenario No 2  | I do not have existing collection | Information (create a collection in your profile) will be in the dropdown  |
| 4 | Scenario No 3  | I unselect all the concepts  | 'Add to Collection' button becomes disabled (clickable)

**Mock-ups:**

- Mock-ups can be found at this URL --> https://marvelapp.com/14d1eb3/screen/25317342
-Check the link below to see the pages
https://drive.google.com/drive/u/0/folders/0B2RCqE113zNxNm9wdThQVXVvaEk

**Technical Assumptions:**

- This is for the Logged-in User.
- No need to consider If the user has collection.

**Comment by djazayeri** [comment]
This works correctly.

Minor complaint is that if I don't have any user collections, but I do have org collections, I would expect to see a similar "you don't have any user collections" message, but instead I just see the org collections.

Also I noticed that if I am not logged in, the global search page has checkboxes next to each search result, but nothing happens when I check/uncheck them (because there is no visible Add To Collection action). It would be better to not show the checkboxes unless you are logged in.

(I don't think either of these are blockers for release.)

**Comment by berkansahan** [comment]
For first paragraph:
this is a good idea but we have chosen this way because it is more simple and clear for the first stage. Plus, we tried to keep that simplicity equally for the other flows. Our suggestion is to continue as it is.

For second paragraph,
We have reviwed and changed it. Unless you are logged in, the checkboxes will not be seen.
@djazayeri

**Comment by djazayeri** [comment]
Second paragraph is fixed (i.e. when not logged in).
I'm fine to leave as-is for what I said in the first paragraph.
