### ISSUE TITLE
Concept / Repository Search / Search, select and add (to existing collection)

### ISSUE THREAD

**Issue by fatmau** [OpenConceptLab/oclapi#427]
As a user
I want to select and add any concept to collection
So that I will select a collection and confirm the action.
**Dependency:**

- #425   

**Acceptance Scenario:**

| No  | Given  | When  | Then  |
| ------------- | ------------- | ------------- | ------------- |
| 1 | I searched for concept with one or multiple result | I select one or multiple results  | Add to Collection appears |
| 2 | Scenario No 1  | I click the dropdown | I see all my existing collections on the list  |
| 3 | Scenario No 2  | I select one of the user collection  | Save button returns actively clickable |
| 4 | Scenario No 3 | I click save button  | Confirmation box appears on the page. |
| 5 | Scenario No 4  | Confirmation box appears on the page | I do not unselect checkbox to add related mappings and I click Confirm button  |
| 6 | Scenario No 5  | I click the Save button | I see concept(s) and 'from' mapping(s) stored in the same source, in the collection |
| 7 | Scenario No 6  | I saved the concepts | I see approval box (yellow background) on the initial page |

**Mock-ups:**

- Mock-ups can be found at this URL --> https://marvelapp.com/14d1eb3/screen/25317356
- Check the link below to see the pages
https://drive.google.com/drive/u/0/folders/0B2RCqE113zNxNm9wdThQVXVvaEk

**Technical Assumptions:**

* This is for the Logged-in User.
* Organisation and personal collections should have different backgrounds.
* When the user refresh the page, it returns initial form.
* When the story is completed, selected concepts should be unselected.

**Comment by djazayeri** [comment]
Major comments:

* When I click on Add To Collection, it shows me a lot of collections that I don't think I should have access to. Is this a bug? I should only see collections in the dropdown if I have permission to write to them. (E.g. I see "EthiopiaNHDD / NCoD-Extended" in the dropdown, but that collection has public access = View, and I am not a member of the org.)
* When I add a concept, and then I try to add it again, it says "References listed below could not be added.
/orgs/CIEL/sources/CIEL/concepts/146869/: Concept or Mapping reference name must be unique in a collection." But it would make a lot more sense if it just said "xyz is already in the collection". (Also, it would be nice if I can add a concept again in order to automatically add any new mappings it has. This could be a different ticket though.)

Minor comments:

* I click Save to add a concept to collection 427, and it works correctly. Then, in another tab where I already had collection 427 open (https://staging.openconceptlab.org/users/djazayeri/collections/427/references/), I reload. It shows me a popup saying "Related mappings stored in the same source are also added to collection." Ideally this popup would not happen unless it's directly following the previous flow. But if it does pop up, at least change the text to "When you added concepts to this collection we automatically added related mappings from the same source".
* After I click Save (which works correctly) if I click Add to Collection again the radio button state and automatically-add-mappings state are preserved. I would expect that state to be reset after I click Save. (But I can live with the current behavior.)

Otherwise things work nicely!

**Comment by djazayeri** [comment]
PS- I don't know if it's a global problem or just my account, but when I look at https://staging.openconceptlab.org/orgs/EthiopiaMOH/  I am not shown as a member. But when I go to https://staging.openconceptlab.org/users/djazayeri/?tab=Organizations it shows me as belonging to this org (and lots of others, maybe all of them).

**Comment by djazayeri** [comment]
Minor UX issue: because the Add To Collection button is so far down the page, when I click it I also have to scroll to find the save button on the popup (full-screen Chrome window in a 15" laptop):

![image](https://cloud.githubusercontent.com/assets/1165236/24292531/bd633e94-10b3-11e7-8174-6c8d07755080.png)

(Not a blocker. I'd just leave this as-is, unless you can think of a trivial fix.)

**Comment by paynejd** [comment]
This appears to be working correctly!
