### ISSUE TITLE
Concept / Detail / Add to collection (to existing collection)

### ISSUE THREAD

**Issue by fatmau** [OpenConceptLab/oclapi#429]
As a user
I want to select and add any concept to collection
So that I will select a collection and confirm the action.
**Dependency:**

- N/A 

**Acceptance Scenario:**

| No  | Given  | When  | Then  |
| ------------- | ------------- | ------------- | ------------- |
| 1 | I see any concept detail | I click 'Add to Collection' button | I see all my existing collections on the list |
| 2 | Scenario No 1  | I select one of the user collection  | Save button returns actively clickable |
| 3 | Scenario No 2 | I click save button  | Info box appears on the page. |
| 4 | Scenario No 3  | Info box appears on the page | I do not unselect checkbox to add related mappings and I click Confirm button  |
| 5 | Scenario No 4  | I click the Save button | I see concept(s) and 'from' mapping(s) in the user collection |
| 6 | Scenario No 5  | I saved the concepts | I see approval box on the initial page |

**Mock-ups:**

- Mock-ups can be found at this URL --> https://marvelapp.com/14d1eb3/screen/25357974
-Check the link below to see the pages
https://drive.google.com/drive/u/0/folders/0B2RCqE113zNxNm9wdThQVXVvaEk

**Technical Assumptions:**

- This is for the Logged-in User.
- Organisation and personal collections should have different backgrounds.
- When the user refresh the page, initial form.

**Comment by djazayeri** [comment]
For the happy path, this functions correctly.

UX problems:

* On this screen the popup grows to be very very long if you have access to lots of collections.
Instead it should behave just like on the global search page (where the popup size is fixed, and it has internal scrolling).
* the "Save" button in the dropdown should say "Add" instead
* the "Close" button in the dialog should say "Cancel" instead

Functional problem:

* If I go to a specific concept version (e.g. https://staging.openconceptlab.org/users/djazayeri/sources/OMRS/concepts/Node/58d4cd391bee0d0051b881c7/details/) and I do Add to Collection from there, it shows me the message "Added the latest versions of concept to the collection. Future updates will not be added automatically" Instead I would have expected the version whose page I was on to be added.

(I incorrectly made some of these same comments on #428 instead of on this issue.)

**Comment by paynejd** [comment]
The "Add to Collection" dropdown only works on the "Details" tab -- it is always empty on the "Mappings" and "History" tabs.

![image](https://cloud.githubusercontent.com/assets/1189689/24551042/dee741b0-15ee-11e7-84ae-4f4704a20774.png)
