### ISSUE TITLE
Concept & Mapping / Add Reference / UI Enhancement

### ISSUE THREAD

**Issue by fatmau** [OpenConceptLab/oclapi#432]
As a user
I want to add references
So that default version of the tab of reference page should be 'Add by Organisation or User'

**Dependency:**
- N\A 

**Acceptance Scenario:**

**Add New References Page**

| No  | ---  |
| ------------- | ------------- |
| 1 | Rename 'Add Multiple References' into 'Add by Organisation or User' |
| 2 | Rename 'Add Single References' into 'Add by URL'  |
| 3 | Switch the location of tabs. So the default version of the page will be 'Add by Organisation or User'  |

**References Page**

| No  | ---  |
| ------------- | ------------- |
| 1 | Delete text link should be like button and more visible  |
| 2 | Select and unselect all the references  |

**Mock-ups:**

- Mock-ups can be found for Add New References Page at this URL --> (https://marvelapp.com/14d1eb3/screen/18176255)
-Click to link below to see the pages
https://drive.google.com/drive/u/0/folders/0B2RCqE113zNxNm9wdThQVXVvaEk

**Comment by berkansahan** [comment]
As a user
I want to add references
So that default version of the tab of reference page should be 'Add by Organisation or User'

**Dependency:**
- N\A 

**Acceptance Scenario:**

| No  | ---  |
| ------------- | ------------- |
| 1 | Rename 'Add Multiple References' into 'Add by Organisation or User' |
| 2 | Rename 'Add Single References' into 'Add by URL'  |
| 3 | Switch the location of tabs. So the default version of the page will be 'Add by Organisation or User'  |


**Mock-ups:**

- Cancel button should appear only when there is no selected concept.

**Comment by berkansahan** [comment]
The gap between select box and sources should be shorter.
for mockup: pls check the file called **#432-2-References Page**
https://drive.google.com/drive/u/0/folders/0B2RCqE113zNxNm9wdThQVXVvaEk
