### ISSUE TITLE
Mapping / Global Search / Search, select and add (to existing collection)

### ISSUE THREAD

**Issue by fatmau** [OpenConceptLab/oclapi#436]
As a user
I want to select and add any mapping to collection
So that I will select a collection and confirm the action.

**Dependency:**

- #434   

**Acceptance Scenario:**

| No  | Given  | When  | Then  |
| ------------- | ------------- | ------------- | ------------- |
| 1 | I searched for mapping with one or multiple result | I select one or multiple results  | Add to Collection appears |
| 2 | Scenario No 1  | I click the dropdown | I see all my existing collections on the list  |
| 3 | Scenario No 2  | I select one of the user collection  | Save button returns actively clickable |
| 4 | Scenario No 3 | I click save button  | Info box appears on the page. |
| 5 | Scenario No 4  | Info box appears on the page | I click Confirm button  |
| 6 | Scenario No 5  | I saved the concepts | I see approval box on the initial page |

**Mock-ups:**

- Mock-ups can be found at this URL --> https://marvelapp.com/--
-Check the link below to see the pages
https://drive.google.com/drive/u/0/folders/0B2RCqE113zNxNm9wdThQVXVvaEk

**Technical Assumptions:**

- This is for the Logged-in User.
- Organisation and personal collections should have different backgrounds.
- When the user refresh the page, initial form.
-When the story is completed, selected concept do not become unselected.

**Comment by paynejd** [comment]
This works correctly, but the confirmation message needs to be modified slightly since it is only possible to add to a single collection at a time. Instead of:
![image](https://cloud.githubusercontent.com/assets/1189689/24551201/a47bc19e-15ef-11e7-9622-7a3c5321b141.png)

Change it to:
`Added the mapping to the collection "collectionOwner / collectionName" successfully`
