### ISSUE TITLE
Concept / API / Add from mapping of concept

### ISSUE THREAD

**Issue by fatmau** [OpenConceptLab/oclapi#443]
As a user
I want to add a concept to any collection
So that API will add 'from' mapping of concept.

**Dependency:**

- N/A

**Acceptance Scenario:**
Collection Name: Test

| Concept Name | Mapping Name  | Mapping from  | Mapping to  |
| ------------- | ------------- | ------------- | ------------- | 
| X  | A  | X  | Y  |
| X  | B  | Y  | X  |

| No  | Given  | When  | Then  |
| ------------- | ------------- | ------------- | ------------- |
| 1 | ---- | I add concept called 'X' to collection called 'Test' via API or add reference page.   | I will see at UI that Mapping A also will be added into collection Test |

**Technical Assumptions:**

- This story is all about API side.

**Comment by berkansahan** [comment]
As a user
I want to add a concept to any collection
So that API will add 'from' mapping of concept.

**Dependency:**

- #423 

**Acceptance Scenario:**
Collection Name: Test

| Concept Name | Mapping Name  | Mapping from  | Mapping to  |
| ------------- | ------------- | ------------- | ------------- | 
| X  | A  | X  | Y  |
| X  | B  | Y  | X  |

| No  | Given  | When  | Then  |
| ------------- | ------------- | ------------- | ------------- |
| 1 | I searched for concept X | I add concept called 'X' to collection called 'Test' and save it   | I will confirm that Mapping A also will be added into collection Test  |

**Technical Assumptions:**

- This story is all about API side.
- No need to consider to see any screen at the end of this story.

**Comment by djazayeri** [comment]
I'm going to mark this as Done, because the behavior is working as written in the first comment.
However we have since decided that this behavior should not be automatic at the API level, because it's only the 80% case, not the 100% case.
