### ISSUE TITLE
Status codes returned when adding collection references are incorrect

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/oclapi#455]
When a reference is created, a 200 status code is returned. Even when an error occurs and a reference is not added (e.g. reference to the same concept/mapping already exists), the request is not honored and a 200 status code is still returned. These status codes should be updated so that they reflect what actually happened. 

201 is normal for an object to be created.

We can have a discussion about the other status codes.

**Comment by emrah-b** [comment]
@paynejd we actually had a discussion about this and decided on 200 because we thought it as an update to the collection resource. 200 is the success status for an update.
We thought of returning 409 Conflict or 400 Bad Request if there were errors. However, in that case, when some references are created and some are not due to errors, error status gave the impression that all was lost. 
In the end we decided that we would return 200 to give the impression that "Your request for update was received". I agree that it is confusing, we'd be happy to discuss. What is your suggestion? (for mixed status case)

**Comment by molgun** [comment]
Hi guys,

What about 207

https://httpstatuses.com/207

**Comment by paynejd** [comment]
+1 for 207. Although 200 still may be appropriate if all internal actions
would have produced a 200.
