### ISSUE TITLE
problem with mapping create API serializer - to_concept_url handling of full URI

### ISSUE THREAD

**Issue by pkshiu** [OpenConceptLab/oclapi#56]
I cannot create internal mappings using the API between internal concepts if I use absolute URL's as explained in the wiki/doc . The Mapping model clean method is failing because it is looking for to_concept field. But the MappingCreateSerializer is returning a "Not Found" error from the "to_concept_url" field.

I can get this to work if I specify the to_concept_url without the host name and the v1 prefix.

POST URL:

http://api.dev.openconceptlab.com/v1/orgs/OMRS/sources/OMRS/concepts/12/mappings/

This is the POST json:

This works:

{"map_type": "q_and_a", "to_concept_url": "/orgs/OMRS/sources/OMRS/concepts/1115/"}

This does NOT work:

{"map_type": "q_and_a", "to_concept_url": "http://api.dev.openconceptlab.com/v1/orgs/OMRS/sources/OMRS/concepts/1115/"}

The to concept (ID 1115) exists, I can use the URL to get to it.

The auth token for "pkshiu":
Authorization: Token acdae20580926ae50c1df17b7ecd445a8efe8d6c

I don't know if there is something wrong with the ConceptReferenceField or the HyperlinkedRelatedField code. If you can fix and/or explain what it is doing it will be helpful.

**Comment by paynejd** [comment]
Will update model along with the updated mapping spec during the February push.

**Comment by MisterNando** [comment]
Estimates:

Original - N/A
Updated - 2h

**Comment by MisterNando** [comment]
I suspect this may be due to the "v1" element in the URL path.  The parser doesn't know where the path info segment ends and the resource path segment begins, so it assumes that the path info segment ("v1/", in this case) is empty.

We can get around this by omitting the "v1" part from the URLs, or by moving "v1" from the path info segment to the resource path segment.

@paynejd , please advise.

**Comment by MisterNando** [comment]
FWIW, I've confirmed that both relative URLs and full ones work if the path info segment is empty (as it is in my local configuration).

**Comment by paynejd** [comment]
I'm not sure I entirely follow but what I'm understanding is that the v1 is
making things break and we can either make v1 part of the resource URLs or
we can remove it entirely. The trend for rest APIs is towards putting
versions in the header rather than in the url itself so my vote is to
remove it.

Is that a big change though? That impacts both the api code and the web
app.

**Comment by MisterNando** [comment]
My vote would be to remove it as well.  @pkshiu , would this have a huge impact on the web app, or just a configuration change?

**Comment by pkshiu** [comment]
It should not be a big deal, as my access to the API is centralized in one module. There will be config changes as well. so just do it and test is all I need. I say go for it.

**Comment by MisterNando** [comment]
@paynejd , @pkshiu, okay, the 'v1' element has been removed.

**Comment by pkshiu** [comment]
So the URL will need to be without the V1 from now, is that correct? I need to update and restart and update dev servers?

**Comment by MisterNando** [comment]
Correct - I already updated the server config (for the API) - you'll just
have to update any code that references the 'v1' URLs.
