### ISSUE TITLE
Mapping create, external sources, should require to_source_url OR to_source_code?

### ISSUE THREAD

**Issue by pkshiu** [OpenConceptLab/oclapi#57]
Found an inconsistency between the doc and the code, not sure which one is right. 

The doc  (https://github.com/OpenConceptLab/oclapi/wiki/mappings#list-mappings-for-a-concept)
says for external mappings, we need `to_source_code`, `to_concept_code`, and `map_type` which seems to make sense, e.g. ANTIMALARIAL MEDICATIONS is mapped to SNOMED (source_code), 61261009 (concept_code there), and ‘SAME-AS’ as type.

But the doc’s example shows it supplying to_source_url, and more importantly, the API is checking and storing to_source_url instead of to_source_code.

Not sure if @MisterNando or @paynejd has an answer? This is stopping me from loading the CIEL mappings.

**Comment by paynejd** [comment]
All sources must be stored in OCL, regardless of whether the concept is "internal" or "external". Meaning, in order to create an "external mapping" the external source must first be defined.

As an example with the CIEL dictionary, if a concept is mapped to `BobsExternalSource:123456` owned by `BobsOrgs`, then `to_source_url` must be set to `/orgs/BobsOrg/sources/BobsExternalSource/` and `to_concept_code` set to `123456`.

From the documentation:

The **from_concept** must always be stored in OCL. There are two types of **to_concepts**:

1. Internal - The **to** concept is stored in OCL
2. External - The **from** source is defined in OCL, but it is just a placeholder

Following are the fields that are required to be set for each type above:

| field | type |
| -------------- | ----- |
| to_concept_url | 1 |
| to_concept_code | 2 |
| to_concept_name | |
| to_source_url | 2 |
