### ISSUE TITLE
Improve performance of concept import script

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/oclapi#72]
Full import of CIEL dictionary (excluding mappings) took 30+ hours to run on an empty database on development server. Note that this did not include any of the mappings, which would increase the time even further. After a performance analysis, propose a "reasonable" run-time and then implement a fix.

Estimated 8 hours of work by Aaron.

**Comment by MisterNando** [comment]
Estimates:

Original - 8h
Updated - 8h

**Comment by MisterNando** [comment]
@pkshiu , can you point me at an import file I can use to test this?  Thanks!

**Comment by pkshiu** [comment]
@MisterNando  On dev, there is a file on the home dir of deploy called 1000_raw.json that you can use.

**Comment by paynejd** [comment]
There are obviously significant implementation differences, but the OpenMRS team indicated that they imported the full 50k terms in the CIEL dictionary into a Lucene instance in <10min. 

Aaron, can I put you in contact with Rafal to discuss options for improving performance?

**Comment by MisterNando** [comment]
Primary bottleneck was the automatic update to the Solr index.  Disabling this operation reduced import time by ~50% (on a sample set of ~3000 records).  Now, rebuild_index must be called upon import completion, but rebuild_index operates on records in bulk, and is several orders of magnitude faster than calling update one record at a time.

I also modified the syntax of import_concepts_to_source to mirror that of import_mappings_to_source.  See wiki page for further details.

**Comment by paynejd** [comment]
That sounds like an improvement, but I'm curious what that adds up to when
you do the import plus the re-index. Because the re-index is also acting on
everything in Solr, not just the CIEL dictionary right? After we import
other dictionaries (which are much larger than the CIEL dictionary), this
could ultimately cause it to take far longer than doing the update while
doing the import? Not sure if I'm understanding this correctly, but this is
important think through because we'll be adding the next dictionary in a
couple of weeks.

Second, what is the status of OCL during an import? Is it locked or is it
just providing results from the older version?



--
Jonathan Payne, MS
615.579.5413
*LinkedIn:* www.linkedin.com/in/jonathandavidpayne
*Skype:* jonathandavidpayne

**Comment by MisterNando** [comment]
rebuild_index need not operate on the entire index.  See full documentation here: http://django-haystack.readthedocs.org/en/latest/management_commands.html#rebuild-index (specifically the "age" parameter).

The OCL API is unstable during an import, so it should be turned off while an import is in progress.  It should resume normal operation after the subsequent index update has completed.

**Comment by paynejd** [comment]
The point still remains that import + re-index will take 10-20 hours with
the new approach, with some time shifted away from the import and over to
the re-index and if the system is inoperable during the process it may not
have bought us too much -- was the system inoperable during the previous
import model, even if it took longer? How long did the import take with 3k?

Given the huge amount of time this is taking it seems that there is
something beyond the method of updating the index.

What were the results of your investigation into the requirement to iterate
through all of the versions for each concept import?

Do you have other ideas how this can be improved?

**Comment by MisterNando** [comment]
For 3000 records, the previous version of import (with index update in real time) took ~90s.  The amended version takes ~40s, and the subsequent index update takes ~5s.

There was never any locking in place around the update, so OCL behavior during an update has always been unstable.  The simplest way to address this would be to have 2 instances in rotation; one active and one inactive.  You would apply the import to the inactive one, and then swap them once complete.

Regarding the other possible area for improvement that I mentioned yesterday, I experimented with that as well, although that only affects indexing time; not import time.  By removing the expensive bit of code, I was able to achieve a ~40% decrease in indexing time, but indexing (in bulk) is relatively cheap compared with the import.

The import is a very unsophisticated operation.  It's merely a repetition of the CREATE operation for each item in the input.  Our options for further improvement at this point are:

1. Make the import strategy more intelligent (instead of one CREATE at a time).
2. Make the CREATE operation more efficient.
3. All of the above.

However, either of the above would exceed the amount of time we've allotted for this task.

**Comment by pkshiu** [comment]
Isn't mongo is very good for write operations? i.e. create should be fast. However, it is also memory intensive, so more memory = better mongo performance?

Solr is the bigger issue, right?

**Comment by MisterNando** [comment]
I don't think Mongo write performance is the issue; I think it's all the
little things that go into the create operation, like looking up the parent
source, checking the write permissions, etc., etc.  In other words, create
isn't just a write; it's a series of reads, and then a write.

**Comment by paynejd** [comment]
PK, Can you please try out a full import with the updated code and let us
know how long both the import and the re-index take?

--
Jonathan Payne, MS
615.579.5413
*LinkedIn:* www.linkedin.com/in/jonathandavidpayne
*Skype:* jonathandavidpayne
